/*

 LEVEL1_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 80 x 19
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level1_mapWidth 80
#define level1_mapHeight 19
#define level1_mapBank 0

extern unsigned char level1_map[];

/* End of LEVEL1_MAP.H */
